### ISSUE TITLE
Implementation of the user stories related with basic cat management features

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#59]
**Base instructions**
For each user story you will have to implement the following files (where xx stands for your action):
Code:
- app/controllers/cats_controller.rb#xx
- app/views/cats/xx.html.erb
Tests:
- spec/controllers/cats_controller.rb#xx
- spec/features/your_feature_name_spec.rb

You can find relevant examples in other repositories:

- Controllers: https://github.com/infusionvlc/infusion/blob/master/app/controllers/ (check out https://github.com/varvet/pundit to learn about user permissions)

- Controller tests: https://github.com/ifmeorg/ifme/tree/master/spec/controllers

- Feature tests: https://github.com/ifmeorg/ifme/tree/master/spec/features

**Related issues**:
- [x] #61 create cat
- [x] #62 edit cat
- [x] #63 list cats (base)
- [x] #64 list cats (volunteer)
- [x] #65 show cat (base)
- [x] #66 show cat (volunteer)
- [x] #67 adopt cat
- [x] #68 sponsor cat
